### ISSUE TITLE
model available

### ISSUE THREAD

**Issue by defenceVT** [SharifAmit/DilatedFCNSegmentation#1]
hello, i want to know if the model and the training code is available?

**Comment by SharifAmit** [comment]
Yes, Ill be uploading the models soon. Im training on some new benchmarks and dataset. So will be uploading all the versions of the models together. Keep your eye on the repo.

**Comment by SharifAmit** [comment]
I have uploaded the models. Please see the repo readme file. So, I'm closing the issue. Regards.

**Comment by LAYning** [comment]
Hello.The link—FCN2s-Dilated-VGG16 can not be opened.Please help me solve the problem.Thank you very much.
