### ISSUE TITLE
Learning from you,thank you!

### ISSUE THREAD

**Issue by LAYning** [SharifAmit/DilatedFCNSegmentation#6]
Hello! I want to do transfer learning from VGG16 and VGG19.But it is always wrong when I write solver.prototxt,train.prototxt and so on.Now I need your help.When do you upload these files？Thank you very much!

**Comment by SharifAmit** [comment]
Uploaded solver, train and val prototxt and also added voc_layers for data loading. Please check Dilated_FCN-2s_VGG16 folder.

**Comment by SharifAmit** [comment]
Also, I'm updating the Readme.md for doing the net surgery, weight loading and also training the neural net. See the updated Readme.md in couple of hours.

**Comment by SharifAmit** [comment]
Updated the readme.me ! Closing this thread !
