### ISSUE TITLE
How to initialize the dilated fc6 layer whose kernel size is 3x3 while vgg16 or vgg19' s the parameter of the fc6 layer is 102760488 ?

### ISSUE THREAD

**Issue by wuyang556** [SharifAmit/DilatedFCNSegmentation#8]

**Comment by SharifAmit** [comment]
You have to first perform net-surgery. Please check this: https://github.com/SharifAmit/DilatedFCNSegmentation/blob/master/surgery-instructions.txt
You can then do training by following these steps : https://github.com/SharifAmit/DilatedFCNSegmentation/blob/master/training-instructions.txt
